# Generated by Django 5.0 on 2024-01-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='password',
            new_name='course',
        ),
    ]
