# Generated by Django 3.2 on 2023-12-19 05:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moviefacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 5, 18, 16, 53140, tzinfo=utc), verbose_name='date published'),
        ),
    ]
